// Generated by FlowBuilder
import React from 'react';

export default function ModernLandingPageCopyPage() {
    return (
        <div className="min-h-screen bg-gray-50 p-8">
            <div className="max-w-4xl mx-auto">
      <div className="flex flex-col gap-8 p-16 ">
        <button className="px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 transition-colors">Click Me</button>
      </div>
      <img src="/placeholder.jpg" alt="Image" className="w-full h-auto rounded-lg" />
      <p style={{ fontSize: 16 }}>Text content</p>
      <label className="flex items-center gap-2"><input type="checkbox" />Checkbox</label>
      <input type="text" placeholder="Enter text..." className="px-3 py-2 border border-gray-300 rounded-lg" />
            </div>
        </div>
    );
}
